name: feupy
channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip

  # Core scientific stack
  - numpy>=1.22
  - scipy>=1.10
  - matplotlib>=3.7
  - pandas>=2.0
  - pyyaml
  - tqdm

  # Astronomy / Gamma-ray tools
  - astropy>=6.0
  - naima>=0.10
  - gammapy=2.0

  # Jupyter ecosystem
  - jupyter
  - ipykernel

  # pip install (editable mode)
  - pip:
      - -e .

variables:
  GAMMAPY_DATA: /home/phoenix/Coding/data/gammapy-datasets/2.0
  FEUPY_DATA: /home/phoenix/Coding/data/feupy-datasets/1.0
