general:
    log: {level: info, filename: null, filemode: null, format: null, datefmt: null}
    outdir: .
    n_jobs: 1
    datasets_file: null
    models_file: null
observations:
    target:
        name: PSR J1826-1256
        position: {frame: icrs, lon: 276.53554166666663 deg, lat: -12.9425 deg}
        model:
            name: PSR J1826-1256
            type: SkyModel
            spectral:
                type: ExpCutoffPowerLawSpectralModel
                parameters:
                - {name: index, value: 1.5}
                - {name: amplitude, value: 1.0e-12, unit: TeV-1 s-1 cm-2}
                - {name: reference, value: 1.0, unit: TeV}
                - {name: lambda_, value: 0.1, unit: TeV-1}
                - {name: alpha, value: 1.0}
    parameters: {livetime: 10.0 h, offset: 0.11 deg, on_region_radius: 0.5 deg, n_obs: 10}
    irfs:
        opt: [South, AverageAz, 20deg, 50h]
    pointing: {angle: 0.0 deg}
datasets:
    geom:
        axes:
            energy: {min: 0.1 TeV, max: 100.0 TeV, nbins: 5, name: energy}
            energy_true: {min: 0.03 TeV, max: 300.0 TeV, nbins: 8, name: energy_true}
    selection: [counts, exposure, background, psf, edisp]
    use_region_center: false
    safe_mask:
        methods: [aeff-default]
        parameters: {}
    containment_correction: false
    acceptance: null
    acceptance_off: null
    alpha: null
sensitivity: {gamma_min: null, n_sigma: null, bkg_syst_fraction: null}
