general:
    log: {level: info, filename: null, filemode: null, format: null, datefmt: null}
    outdir: .
    n_jobs: 1
    datasets_file: null
    models_file: null
roi:
    target:
        name: LHAASO J1825-1326
        position: {frame: icrs, lon: 276.45 deg, lat: -13.45 deg}
        model:
            name: LHAASO J1825-1326
            type: SkyModel
            spectral:
                type: ExpCutoffPowerLawSpectralModel
                parameters:
                - {name: index, value: 1.5}
                - {name: amplitude, value: 1.0e-12, unit: TeV-1 s-1 cm-2}
                - {name: reference, value: 1.0, unit: TeV}
                - {name: lambda_, value: 0.1, unit: TeV-1}
                - {name: alpha, value: 1.0}
    region_radius: 1.0 deg
    catalogs: all
energy_range: {min: 0.1 TeV, max: null}
