name: feupy-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout FeuPy Data
        uses: actions/checkout@v4
        with:
          repository: rubensjrcosta/feupy-data
          path: feupy-data
          ref: v1.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Set FEUPY_DATA
        run: |
          echo "FEUPY_DATA=${{ github.workspace }}/feupy-data/feupy-datasets/1.0" >> "$GITHUB_ENV"

      - name: Show dependency versions
        run: |
          python -c "import gammapy, regions; print('gammapy:', gammapy.__version__); print('regions:', regions.__version__)"
          echo "FEUPY_DATA=$FEUPY_DATA"
          ls "$FEUPY_DATA"

      - name: Run tests
        run: pytest -v
